# Used this for help on reversing syscall wrappers
# https://specterdev.blogspot.com/2016/08/ps4-reversing-libkernelsprx-system-call.html

# Might be outdated, but basing this information on...
# https://cturt.github.io/ps4.html
freebsd_max_syscall_num = 532
sce_max_syscall_num = 672

# Generic syscall function names
freebsd_generic = 'sys_'
sce_generic     = 'sys_sce_'

# FreeBSD Syscalls: https://github.com/freebsd/freebsd/blob/release/9.2.0/sys/kern/syscalls.master
# Sony Syscalls: http://www.psdevwiki.com/ps4/Syscalls
# PS4 Version: >1.76?
syscall_table = {
    # FreeBSD syscalls
    0:      'nosys',
    1:      'sys_exit',
    2:      'fork',
    3:      'read',
    4:      'write',
    5:      'open',
    6:      'close',
    7:      'wait4',
    8:      'creat',
    9:      'link',
    10:     'unlink',
    11:     'execv',
    12:     'chdir',
    116:    'gettimeofday',
    137:    'sys_rmdir',
    532:    'wait6',

    # Sony syscalls
    588:    'sys_mname',
    589:    'sys_dynlib_dlopen',
    590:    'sys_dynlib_dlclose',
    591:    'sys_dynlib_dlsym',
    592:    'sys_dynlib_get_list',
    593:    'sys_dynlib_get_info',
    594:    'sys_dynlib_load_prx',
    595:    'sys_dynlib_unload_prx',
    596:    'sys_dynlib_do_copy_relocations',
    597:    'sys_dynlib_prepare_dlclose',
    598:    'sys_dynlib_get_proc_param',
    599:    'sys_dynlib_process_needed_and_relocate',
    600:    'sys_sandbox_path',
    601:    'sys_mdbg_service',
    602:    'sys_randomized_path',
    603:    'sys_rdup',
    604:    'sys_dl_get_metadata',
    605:    'sys_workaround8849',
    606:    'sys_is_development_mode',
    607:    'sys_get_self_auth_info',
    608:    'sys_dynlib_get_info_ex',
    609:    'sys_budget_getid',
    610:    'sys_budget_get_ptype',
    611:    'sys_get_paging_stats_of_all_threads',
    612:    'sys_get_proc_type_info',
    613:    'sys_get_resident_count',
    614:    'sys_prepare_to_suspend_process',
    615:    'sys_get_resident_fmem_count',
    616:    'sys_thr_get_name',
    617:    'sys_set_gpo',
    618:    'sys_get_paging_stats_of_all_objects',
    619:    'sys_test_debug_rwmem',
    620:    'sys_free_stack',
    621:    'sys_suspend_system',
    622:    'sys_ipmimgr_call',
    623:    'sys_get_gpo',
    624:    'sys_get_vm_map_timestamp',
    625:    'sys_opmc_set_hw',
    626:    'sys_opmc_get_hw',
    627:    'sys_get_cpu_usage_all',
    628:    'sys_mmap_dmem',
    629:    'sys_physhm_open',
    630:    'sys_physhm_unlink',
    631:    'sys_resume_internal_hdd',
    632:    'sys_thr_suspend_ucontext',
    633:    'sys_thr_resume_ucontext',
    634:    'sys_thr_get_ucontext',
    635:    'sys_thr_set_ucontext',
    636:    'sys_set_timezone_info',
    637:    'sys_set_phys_fmem_limit',
    638:    'sys_utc_to_localtime',
    639:    'sys_localtime_to_utc',
    640:    'sys_set_uevt',
    641:    'sys_get_cpu_usage_proc',
    642:    'sys_get_map_statistics',
    643:    'sys_set_chicken_switches',
    644:    'sys_extend_page_table_pool',
    645:    'sys_#645',
    646:    'sys_get_kernel_mem_statistics',
    647:    'sys_get_sdk_compiled_version',
    648:    'sys_app_state_change',
    649:    'sys_dynlib_get_obj_member',
    650:    'sys_budget_get_ptype_of_budget',
    651:    'sys_prepare_to_resume_process',
    652:    'sys_process_terminate',
    653:    'sys_blockpool_open',
    654:    'sys_blockpool_map',
    655:    'sys_blockpool_unmap',
    656:    'sys_dynlib_get_info_for_libdbg',
    657:    'sys_blockpool_batch',
    658:    'sys_fdatasync',
    659:    'sys_dynlib_get_list2',
    660:    'sys_dynlib_get_info2',
    661:    'sys_aio_submit',
    662:    'sys_aio_multi_delete',
    663:    'sys_aio_multi_wait',
    664:    'sys_aio_multi_poll',
    665:    'sys_aio_get_data',
    666:    'sys_aio_multi_cancel',
    667:    'sys_get_bio_usage_all',
    668:    'sys_aio_create',
    669:    'sys_aio_submit_cmd',
    670:    'sys_aio_init',
    671:    'sys_get_page_table_stats',
    672:    'sys_dynlib_get_list_for_libdbg',
}
